### ISSUE TITLE
integral todo list

### ISSUE THREAD

**Issue by Akuli** [Akuli/math-derivations#1]
- [ ] `int_a^b + int_b^c = int_a^c` when `a<b<c`
- [ ] same as above with all numbers `a,b,c`, and how integrals have to be defined for it to work
- [ ] integral average
- [ ] fundamental theorem of calc part 1, with integral average
- [ ] antiderivatives and everything related to them
