### ISSUE TITLE
vectors todo list

### ISSUE THREAD

**Issue by Akuli** [Akuli/math-derivations#2]
- [ ] 2x2 determinant
    - [ ] definition with row vectors, area and arrow direction
    - [ ] what if row is vector sum
    - [ ] calculating formula
- [ ] 3x3 determinant
    - [ ] definition with row vectors, parallelepiped volume and hand rules
    - [ ] what if row is vector sum
    - [ ] calculating formula
- [ ] cross product
    - [ ] definition with area and hand rule
    - [ ] combining cross product and dot product --> 3x3 determinant
    - [ ] why putting `i j k` for top row of 3x3 determinant calculates cross product
