### ISSUE TITLE
derivative and limit todo list

### ISSUE THREAD

**Issue by Akuli** [Akuli/math-derivations#4]
- [ ] derivative of sin and cos, with and without location and speed
- [ ] derivatives of exponent functions
- [ ] derivative of ln with chain rule (assume that it exists)
- [ ] alternative definition of derivative: `lim_(t -> x) (f(t)-f(x))/(t-x)`
- [ ] derivative exists => is continuous
- [ ] limits with infinity
    - [ ] `lim_(x -> oo)`
    - [ ] lim = oo
    - [ ] how to convert derivative rule derivations so that they apply for these as well
- [ ] ensure that derivative-vector.html doesn't say "derivative of f" when it should say "derivative of g" (not sure if i fixed this yet)
